bumped up the tools version

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -1,5 +1,5 @@
 # --------------------------------------------------------------------------------
-# This workflow was automatically generated by ActionBuilderTool 2.1.0 (89).
+# This workflow was automatically generated by ActionBuilderTool 2.1.0 (90).
 # (see https://github.com/elegantchaos/ActionBuilderCore for more details)
 # --------------------------------------------------------------------------------
 
@@ -9,8 +9,8 @@ on: [push, pull_request]
 
 jobs:
 
-    macOS-swift57:
-        name: macOS (Swift 5.7)
+    macOS-swift59:
+        name: macOS (Swift 5.9)
         runs-on: macos-13
         steps:
         - name: Checkout
@@ -22,11 +22,11 @@ jobs:
         - name: Select Swift
           uses: beeauvin/swiftly-swift@v1
           with:
-            swift-version: "5.7"
-        - name: Check Swift Version
+            swift-version: "5.9"
+        - name: Swift Version
           run: swift --version
         - name: Build (release)
-          run: swift build --configuration release
+          run: swift build --configuration release --quiet
         - name: Test (release XCTest)
           run: |
             set -o pipefail
@@ -51,7 +51,7 @@ jobs:
           uses: beeauvin/swiftly-swift@v1
           with:
             swift-version: "6.1"
-        - name: Check Swift Version
+        - name: Swift Version
           run: swift --version
         - name: Build (release)
           run: swift build --configuration release --quiet
@@ -65,8 +65,8 @@ jobs:
             swift test --disable-xctest --configuration release | xcbeautify --quiet --disable-logging --renderer github-actions
 
 
-    xcode-swift57:
-        name: iOS/tvOS/watchOS (Swift 5.7, Xcode 14.2)
+    xcode-swift59:
+        name: iOS/tvOS/visionOS/watchOS (Swift 5.9, Xcode 15.2)
         runs-on: macos-13
         steps:
         - name: Checkout
@@ -78,7 +78,7 @@ jobs:
         - name: Select Xcode Version
           run: |
             ls -d /Applications/Xcode* > logs/xcode-versions.log
-            sudo xcode-select -s /Applications/Xcode_14.2.app
+            sudo xcode-select -s /Applications/Xcode_15.2.app
             xcodebuild -version
             swift --version
         - name: Detect Workspace & Scheme (iOS)
@@ -103,7 +103,7 @@ jobs:
             source "setup.sh"
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
             set -o pipefail
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 14" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone SE (3rd generation)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
         - name: Detect Workspace & Scheme (tvOS)
           run: |
             WORKSPACE="Matchable.xcworkspace"
@@ -127,6 +127,29 @@ jobs:
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
             set -o pipefail
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV 4K (3rd generation)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
+        - name: Detect Workspace & Scheme (visionOS)
+          run: |
+            WORKSPACE="Matchable.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+              WORKSPACE="."
+              GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Matchable-Package || true))
+              if [[ $GOTPACKAGE != "" ]]
+              then
+                SCHEME="Matchable-Package"
+              else
+                SCHEME="Matchable"
+              fi
+            else
+              SCHEME="Matchable-visionOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform visionOS > logs/download-visionOS.log" > setup.sh
+        - name: Test (visionOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            set -o pipefail
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Vision Pro" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-visionOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
         - name: Detect Workspace & Scheme (watchOS)
           run: |
             WORKSPACE="Matchable.xcworkspace"
@@ -159,7 +182,7 @@ jobs:
 
 
     xcode-swift61:
-        name: iOS/tvOS/watchOS (Swift 6.1, Xcode 16.4.0)
+        name: iOS/tvOS/visionOS/watchOS (Swift 6.1, Xcode 16.4.0)
         runs-on: macos-15
         steps:
         - name: Checkout
@@ -196,7 +219,7 @@ jobs:
             source "setup.sh"
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
             set -o pipefail
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 14" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone SE (3rd generation)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
         - name: Detect Workspace & Scheme (tvOS)
           run: |
             WORKSPACE="Matchable.xcworkspace"
@@ -220,6 +243,29 @@ jobs:
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
             set -o pipefail
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV 4K (3rd generation)" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
+        - name: Detect Workspace & Scheme (visionOS)
+          run: |
+            WORKSPACE="Matchable.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+              WORKSPACE="."
+              GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Matchable-Package || true))
+              if [[ $GOTPACKAGE != "" ]]
+              then
+                SCHEME="Matchable-Package"
+              else
+                SCHEME="Matchable"
+              fi
+            else
+              SCHEME="Matchable-visionOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'; xcodebuild -downloadPlatform visionOS > logs/download-visionOS.log" > setup.sh
+        - name: Test (visionOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            set -o pipefail
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Vision Pro" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-visionOS-test-release.log | xcbeautify --quiet --disable-logging --renderer github-actions
         - name: Detect Workspace & Scheme (watchOS)
           run: |
             WORKSPACE="Matchable.xcworkspace"
